---
- name: Install .NET Core
  yum:
    name: "dotnet-sdk-{{ dotnet_version_amazon }}"
    state: present
- name: configuring required version of Dotnet
  template:
    src: /home/vamsi/Dotnet/templates/version.j2
    dest: /home/vamsi/global.json
