---
- name: Install .NET Core
  apt:
    name: "dotnet{{ dotnet_version }}"
    state: present
- name: configuring required version of Dotnet
  template:
    src: /home/vamsi/Dotnet/templates/version.j2
    dest: /home/vamsi/global.json
