---
# tasks file for php
- name: Import another playbook as a separate entity
  import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian" 
- name: Import another playbook as a separate entity
  import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
